vault:
  enabled: false

replicaCount: 2

image:
  name: nginx:1.11
  pullPolicy: IfNotPresent

nameOverride: "ruby-app"
fullnameOverride: "ruby-app"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

env:
  open: []
  secret: []

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - ruby.domain.com
  tls:
    - secretName: ruby-tls
      hosts:
        - ruby.domain.com

nodeSelector: {}

tolerations: []

affinity: {}

